#!/usr/bin/env python
import os
import platform
from pathlib import Path

import cpuinfo
import numpy
import simde_py
from setuptools import Extension, setup

NOOP = "-Wabi"


def is_macos() -> bool:
    return platform.system() == "Darwin"


def is_x86_64() -> bool:
    return platform.machine() == "x86_64"


def is_arm64() -> bool:
    return platform.machine() == "arm64"


def has_flag(flag: str) -> bool:
    info = cpuinfo.get_cpu_info()
    flags = info.get("flags", [])
    return flag in flags


def simd_flags() -> list[str]:
    """SIMD compiler flags for x86_64.

    `QSEEK_SIMD_FLAGS` sets the flags explicitly, e.g. for portable wheels that
    must not depend on the build machine. By default the flags are detected from
    the build machine's CPU.
    """
    if not is_x86_64():
        return []
    flags = os.environ.get("QSEEK_SIMD_FLAGS")
    if flags is not None:
        return flags.split()
    return [
        compiler_flag
        for compiler_flag, cpu_flag in (("-mfma", "fma"), ("-mavx2", "avx2"))
        if has_flag(cpu_flag)
    ]


def write_build_info(simd_flags: list[str]) -> None:
    """Record the SIMD flags, qseek checks them against the CPU at import."""
    build_info = Path(__file__).parent / "src" / "qseek" / "ext" / "_build.py"
    build_info.write_text(
        '"""Build information, generated by setup.py."""\n\n'
        f"SIMD_FLAGS: tuple[str, ...] = {tuple(simd_flags)!r}\n"
    )


SIMD_FLAGS = simd_flags()
write_build_info(SIMD_FLAGS)

setup(
    ext_modules=[
        Extension(
            "qseek.ext.array_tools",
            sources=["src/qseek/ext/array_tools.c"],
            include_dirs=[numpy.get_include()],
            extra_compile_args=[
                "-Xpreprocessor" if is_macos() else NOOP,
                "-fopenmp",
                "-O3",
                "-flto",
            ],
            extra_link_args=[
                "-lomp" if is_macos() else "-lgomp",
            ],
        ),
        Extension(
            "qseek.ext.delay_sum",
            sources=["src/qseek/ext/delay_sum.c"],
            include_dirs=[numpy.get_include(), simde_py.get_include()],
            extra_compile_args=[
                "-Xpreprocessor" if is_macos() else NOOP,
                "-fopenmp",
                "-O3",
                "-flto",
                *SIMD_FLAGS,
            ],
            extra_link_args=[
                "-lomp" if is_macos() else "-lgomp",
            ],
        ),
    ]
)
