name: Deploy Docs

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: 3.12
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v6
        with:
          key: zensical-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            zensical-
      - run: pip install .[docs] ghp-import
      - run: zensical build --clean
      - name: Publish to the gh-pages branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          ghp-import --no-jekyll --push --force site
